name: Basic CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  docker:
    name: Prepare base image, fix, test and build SDK
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Debug
        run: |
          echo "github.ref -> ${{ github.ref }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare base image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.IMG_NAME }}
      - name: Fix and Lint
        run: |
          docker run --rm \
            -e API_BASE_URL="${{ secrets.API_BASE_URL }}" \
            -e FRANCHISE_REGISTRY_CONTRACT="${{ secrets.FRANCHISE_REGISTRY_CONTRACT }}" \
            -e RPC_PROVIDER_URL="${{ secrets.RPC_PROVIDER_URL }}" \
            -e WALLET_PRIVATE_KEY="${{ secrets.WALLET_PRIVATE_KEY }}" \
           "${{ env.IMG_NAME }}" -- fix
      - name: Test
        run: |
          docker run --rm \
            -e API_BASE_URL="${{ secrets.API_BASE_URL }}" \
            -e FRANCHISE_REGISTRY_CONTRACT="${{ secrets.FRANCHISE_REGISTRY_CONTRACT }}" \
            -e RPC_PROVIDER_URL="${{ secrets.RPC_PROVIDER_URL }}" \
            -e WALLET_PRIVATE_KEY="${{ secrets.WALLET_PRIVATE_KEY }}" \
           "${{ env.IMG_NAME }}" -- test
      - name: Build SDK
        run: |
          docker run --rm \
            -e API_BASE_URL="${{ secrets.API_BASE_URL }}" \
            -e FRANCHISE_REGISTRY_CONTRACT="${{ secrets.FRANCHISE_REGISTRY_CONTRACT }}" \
            -e RPC_PROVIDER_URL="${{ secrets.RPC_PROVIDER_URL }}" \
            -e WALLET_PRIVATE_KEY="${{ secrets.WALLET_PRIVATE_KEY }}" \
            "${{ env.IMG_NAME }}" -- build

