name: Build and Test

on:
  workflow_call:
    inputs:
      api_base_url:
        required: true
        type: secret
      franchise_registry_contract:
        required: true
        type: secret
      relationship_module_contract:
        required: true
        type: secret
      licensing_module_contract:
        required: true
        type: secret
      collect_module_contract:
        required: true
        type: secret
      rpc_provider_url:
        required: true
        type: secret
      wallet_private_key:
        required: true
        type: secret

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    env:
      ## To use Remote Caching, uncomment the next lines and follow the steps below.
      # TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      # TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      API_BASE_URL: ${{ inputs.api_base_url }}
      FRANCHISE_REGISTRY_CONTRACT: ${{ inputs.franchise_registry_contract }}
      RELATIONSHIP_MODULE_CONTRACT: ${{ inputs.relationship_module_contract }}
      LICENSING_MODULE_CONTRACT: ${{ inputs.licensing_module_contract }}
      COLLECT_MODULE_CONTRACT: ${{ inputs.collect_module_contract }}
      RPC_PROVIDER_URL: ${{ inputs.rpc_provider_url }}
      WALLET_PRIVATE_KEY: ${{ inputs.wallet_private_key }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.8.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Fix
        run: pnpm fix

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build