name: External PR Secure

on:
  workflow_run:
    workflows: ["External PR Insecure"]
    types:
      - completed

jobs:
  build_and_test:
    uses: ./.github/workflows/build-and-test.yaml 
    with:
      api_base_url: ${{ secrets.API_BASE_URL }} 
      franchise_registry_contract: ${{ secrets.FRANCHISE_REGISTRY_CONTRACT }}
      relationship_module_contract: ${{ secrets.RELATIONSHIP_MODULE_CONTRACT }}
      licensing_module_contract: ${{ secrets.LICENSING_MODULE_CONTRACT }}
      collect_module_contract: ${{ secrets.COLLECT_MODULE_CONTRACT }}
      rpc_provider_url: ${{ secrets.RPC_PROVIDER_URL }}
      wallet_private_key: ${{ secrets.WALLET_PRIVATE_KEY }}